# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=200)),
                ('login_text', models.CharField(max_length=200)),
                ('password_text', models.CharField(max_length=200)),
            ],
        ),
    ]
