# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Pass_info',
        ),
    ]
