# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_auto_20171104_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('key', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='pass_info',
            name='login_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pass_info',
            name='password_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pass_info',
            name='source_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='pass_info',
            name='crypto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='passes.Crypto'),
            preserve_default=False,
        ),
    ]
