# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_auto_20171117_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='nonce',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
