# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_auto_20171118_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_info',
            name='crypto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passes.Crypto'),
        ),
    ]
