# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_auto_20171118_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='nonce',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='tag',
            field=models.BinaryField(),
        ),
    ]
