# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0006_auto_20171118_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_info',
            name='login_text',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pass_info',
            name='password_text',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pass_info',
            name='source_text',
            field=models.BinaryField(),
        ),
    ]
