# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0007_auto_20171118_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='key',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='tag',
        ),
        migrations.AddField(
            model_name='crypto',
            name='nonce_l',
            field=models.BinaryField(default=b'0'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='nonce_p',
            field=models.BinaryField(default=b'0'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='nonce_s',
            field=models.BinaryField(default=b'0'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='tag_l',
            field=models.BinaryField(default=b'0'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='tag_p',
            field=models.BinaryField(default=b'0'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='tag_s',
            field=models.BinaryField(default=b'0'),
        ),
    ]
