# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0008_auto_20171118_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='pub_date',
            field=models.DateTimeField(default='2017-10-10 00:00', verbose_name='date created'),
        ),
    ]
