# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0009_crypto_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 13, 30, 11, 864912, tzinfo=utc), verbose_name='date created'),
        ),
    ]
