# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0014_crypto_cr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass_info',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
