# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0015_pass_info_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass_info',
            old_name='user',
            new_name='userid',
        ),
    ]
